@echo off

REM Should be called from Build_uf_xxxx.bat


call bdf2ufont %UFARGS% "bdf/04b_03-8.bdf"
call bdf2ufont %UFARGS% "bdf/04b_03b-8.bdf"
call bdf2ufont %UFARGS% "bdf/04B_08-8.bdf"
call bdf2ufont %UFARGS% "bdf/10x20.bdf"
call bdf2ufont %UFARGS% "bdf/11S0BLT.bdf"
call bdf2ufont %UFARGS% "bdf/198five132.bdf"
call bdf2ufont %UFARGS% "bdf/52 Sphereoids.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/5x7.bdf"
call bdf2ufont %UFARGS% "bdf/5x8.bdf"
call bdf2ufont %UFARGS% "bdf/6px2bus.ttf12.bdf"
call bdf2ufont %UFARGS% "bdf/6x10.bdf"
call bdf2ufont %UFARGS% "bdf/6x12.bdf"
call bdf2ufont %UFARGS% "bdf/6x13.bdf"
call bdf2ufont %UFARGS% "bdf/76London.otf28.bdf"
call bdf2ufont %UFARGS% "bdf/76London38.bdf"
call bdf2ufont %UFARGS% "bdf/76London84.bdf"
call bdf2ufont %UFARGS% "bdf/7x13.bdf"
call bdf2ufont %UFARGS% "bdf/7x14.bdf"
call bdf2ufont %UFARGS% "bdf/8x13.bdf"
call bdf2ufont %UFARGS% "bdf/9x18.bdf"
call bdf2ufont %UFARGS% "bdf/actionman132.bdf"
call bdf2ufont %UFARGS% "bdf/AlliedEngineGreased96.bdf"
call bdf2ufont %UFARGS% "bdf/AmazDooMRightOutline72.bdf"
call bdf2ufont %UFARGS% "bdf/AndroidClock32.bdf"
call bdf2ufont %UFARGS% "bdf/AndroidClock111.bdf"
call bdf2ufont %UFARGS% "bdf/AndroidClock180.bdf"
call bdf2ufont %UFARGS% "bdf/arial16.bdf"
call bdf2ufont %UFARGS% "bdf/AssemblerBold52.bdf"
call bdf2ufont %UFARGS% "bdf/AstronomicMono36.bdf"
call bdf2ufont %UFARGS% "bdf/atari-small.bdf"
call bdf2ufont %UFARGS% "bdf/Bauhaus-Demi20.bdf"
call bdf2ufont %UFARGS% "bdf/Bauhaus-Demi36.bdf"
call bdf2ufont %UFARGS% "bdf/BerlinerGroteskBQ-Light34.bdf"
call bdf2ufont %UFARGS% "bdf/BerlinerGroteskBQ-Light96.bdf"
call bdf2ufont %UFARGS% "bdf/CachetStd-Bold.otf180.bdf"
call bdf2ufont %UFARGS% "bdf/CachetStd-Bold.otf214.bdf"
call bdf2ufont %UFARGS% "bdf/CgYearbookSolid.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/CircleD51.bdf"
call bdf2ufont %UFARGS% "bdf/Clipe Bold.ttf190.bdf"
call bdf2ufont %UFARGS% "bdf/clock92.bdf"
call bdf2ufont %UFARGS% "bdf/CollegiateBlackFLF.otf170.bdf"
call bdf2ufont %UFARGS% "bdf/Colony Wars Normal.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/comicsans20.bdf"
call bdf2ufont %UFARGS% "bdf/Commador Normal.ttf160.bdf"
call bdf2ufont %UFARGS% "bdf/Commador Wide Normal.ttf160.bdf"
call bdf2ufont %UFARGS% "bdf/consola14.bdf"
call bdf2ufont %UFARGS% "bdf/consola24.bdf"
call bdf2ufont %UFARGS% "bdf/consola40.bdf"
call bdf2ufont %UFARGS% "bdf/consola96.bdf"
call bdf2ufont %UFARGS% "bdf/ContinuumMedium18.bdf"
call bdf2ufont %UFARGS% "bdf/ContinuumMedium33.bdf"
call bdf2ufont %UFARGS% "bdf/CorneliusMaurits34.bdf"
call bdf2ufont %UFARGS% "bdf/courr24.bdf"
call bdf2ufont %UFARGS% "bdf/cu12.bdf"
call bdf2ufont %UFARGS% "bdf/Curveless.ttf38.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf11.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf16.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf20.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf26.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf30.bdf"
call bdf2ufont %UFARGS% "bdf/DejaVuSans.ttf36.bdf"
call bdf2ufont %UFARGS% "bdf/efont_b24.bdf"
call bdf2ufont %UFARGS% "bdf/etl24.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF24.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF34.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF44.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF52.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF72.bdf"
call bdf2ufont %UFARGS% "bdf/EUROCAPS.TTF96.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf12.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf18.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf32.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf52.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/FreeSans.ttf108.bdf"
call bdf2ufont %UFARGS% "bdf/FutureHEBold50.bdf"
call bdf2ufont %UFARGS% "bdf/GeoPlainHollow32.bdf"
call bdf2ufont %UFARGS% "bdf/GosmickSans30.bdf"
call bdf2ufont %UFARGS% "bdf/GosmickSans50.bdf"
call bdf2ufont %UFARGS% "bdf/GosmickSans92.bdf"
call bdf2ufont %UFARGS% "bdf/HeberlingCasualNFBold30.bdf"
call bdf2ufont %UFARGS% "bdf/HeberlingCasualNFBold50.bdf"
call bdf2ufont %UFARGS% "bdf/helvr12.bdf"
call bdf2ufont %UFARGS% "bdf/helvr24.bdf"
call bdf2ufont %UFARGS% "bdf/jhm_b34.bdf"
call bdf2ufont %UFARGS% "bdf/LCDRegular51.bdf"
call bdf2ufont %UFARGS% "bdf/Legacy Serif Md ITC TT Medium.ttf28.bdf"
call bdf2ufont %UFARGS% "bdf/Legacy Serif Md ITC TT Medium.ttf34.bdf"
call bdf2ufont %UFARGS% "bdf/Legacy Serif Md ITC TT Medium.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/Legacy Serif Md ITC TT Medium.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/Legacy Serif Md ITC TT Medium.ttf84.bdf"
call bdf2ufont %UFARGS% "bdf/Leger-Regular16.bdf"
call bdf2ufont %UFARGS% "bdf/Leger-Regular33.bdf"
call bdf2ufont %UFARGS% "bdf/levenimmt132.bdf"
call bdf2ufont %UFARGS% "bdf/Luftwaffe Regular.ttf32.bdf"
call bdf2ufont %UFARGS% "bdf/Luftwaffe Regular.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/Luftwaffe Regular.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/Luftwaffe Regular.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/luggageroundregular36.bdf"
call bdf2ufont %UFARGS% "bdf/MA Sexy.ttf32.bdf"
call bdf2ufont %UFARGS% "bdf/Mad scientist.ttf32.bdf"
call bdf2ufont %UFARGS% "bdf/Mad scientist.ttf34.bdf"
call bdf2ufont %UFARGS% "bdf/Maetl Light.ttf30.bdf"
call bdf2ufont %UFARGS% "bdf/Maetl Light.ttf32.bdf"
call bdf2ufont %UFARGS% "bdf/Maetl.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/MainframeBB14.bdf"
call bdf2ufont %UFARGS% "bdf/MainframeBB24.bdf"
call bdf2ufont %UFARGS% "bdf/MainframeBB36.bdf"
call bdf2ufont %UFARGS% "bdf/MaiTai36.bdf"
call bdf2ufont %UFARGS% "bdf/MaiTai96.bdf"
call bdf2ufont %UFARGS% "bdf/Malstock ITC TT.ttf92.bdf"
call bdf2ufont %UFARGS% "bdf/MicroTechnicExtOutline.otf32.bdf"
call bdf2ufont %UFARGS% "bdf/MicroTechnicExtOutline.otf36.bdf"
call bdf2ufont %UFARGS% "bdf/Midevil Normal.ttf36.bdf"
call bdf2ufont %UFARGS% "bdf/MilleniumBdExBTBoldExtended50.bdf"
call bdf2ufont %UFARGS% "bdf/mingliu44.bdf"
call bdf2ufont %UFARGS% "bdf/Miss Ellen.ttf36.bdf"
call bdf2ufont %UFARGS% "bdf/namco36.bdf"
call bdf2ufont %UFARGS% "bdf/namco91.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thick BRK.ttf20.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thick BRK.ttf44.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thick BRK.ttf84.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thick BRK.ttf100.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thick BRK.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf16.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf31.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf84.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf100.bdf"
call bdf2ufont %UFARGS% "bdf/Nanosecond Thin BRK.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/ncenr10.bdf"
call bdf2ufont %UFARGS% "bdf/neuropolitical24.bdf"
call bdf2ufont %UFARGS% "bdf/neuropolitical28.bdf"
call bdf2ufont %UFARGS% "bdf/neuropolitical40.bdf"
call bdf2ufont %UFARGS% "bdf/nimbus14.bdf"
call bdf2ufont %UFARGS% "bdf/notoSerif36.bdf"
call bdf2ufont %UFARGS% "bdf/Orbiteer-Bold30.bdf"
call bdf2ufont %UFARGS% "bdf/OrbonITCStd.otf16.bdf"
call bdf2ufont %UFARGS% "bdf/OrbonITCStd.otf32.bdf"
call bdf2ufont %UFARGS% "bdf/proof9x16.bdf"
call bdf2ufont %UFARGS% "bdf/QuarxOutline26.bdf"
call bdf2ufont %UFARGS% "bdf/QuarxOutline40.bdf"
call bdf2ufont %UFARGS% "bdf/QuerroundRegular33.bdf"
call bdf2ufont %UFARGS% "bdf/QuerroundRegular96.bdf"
call bdf2ufont %UFARGS% "bdf/QuerroundRegular150.bdf"
call bdf2ufont %UFARGS% "bdf/racer102.bdf"
call bdf2ufont %UFARGS% "bdf/racer140.bdf"
call bdf2ufont %UFARGS% "bdf/racer180.bdf"
call bdf2ufont %UFARGS% "bdf/razer.bdf"
call bdf2ufont %UFARGS% "bdf/ReversionBroken34.bdf"
call bdf2ufont %UFARGS% "bdf/RevueHollow180.bdf"
call bdf2ufont %UFARGS% "bdf/RiskBold38.bdf"
call bdf2ufont %UFARGS% "bdf/rought18.bdf"
call bdf2ufont %UFARGS% "bdf/Saved By Zero.ttf24.bdf"
call bdf2ufont %UFARGS% "bdf/Saved By Zero.ttf50.bdf"
call bdf2ufont %UFARGS% "bdf/Schwaben Alt Bold.ttf40.bdf"
call bdf2ufont %UFARGS% "bdf/Schwaben Alt Bold.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/screen8x16.bdf"
call bdf2ufont %UFARGS% "bdf/shadow-bold.bdf"
call bdf2ufont %UFARGS% "bdf/shadow.bdf"
call bdf2ufont %UFARGS% "bdf/sinsabold40.bdf"
call bdf2ufont %UFARGS% "bdf/SinsOfficinaSans84.bdf"
call bdf2ufont %UFARGS% "bdf/snap.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss.otf28.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss.otf34.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss.otf50.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss.otf84.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonNormal.otf36.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonNormal.otf96.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonNormal.otf190.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf28.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf34.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf50.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf84.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf109.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf132.bdf"
call bdf2ufont %UFARGS% "bdf/TeutonWeiss-Bold.otf180.bdf"
call bdf2ufont %UFARGS% "bdf/times16.bdf"
call bdf2ufont %UFARGS% "bdf/TlwgTypewriter50.bdf"
call bdf2ufont %UFARGS% "bdf/ubuntu-l20.bdf"
call bdf2ufont %UFARGS% "bdf/ubuntu-l24.bdf"
call bdf2ufont %UFARGS% "bdf/ubuntu-r12.bdf"
call bdf2ufont %UFARGS% "bdf/ubuntu-r22.bdf"
call bdf2ufont %UFARGS% "bdf/ubuntu-r32.bdf"
call bdf2ufont %UFARGS% "bdf/UbuntuMono-R36.bdf"
call bdf2ufont %UFARGS% "bdf/unicode18.bdf"
call bdf2ufont %UFARGS% "bdf/unicode36.bdf"
call bdf2ufont %UFARGS% "bdf/unicode50.bdf"
call bdf2ufont %UFARGS% "bdf/unicode72.bdf"
call bdf2ufont %UFARGS% "bdf/unicode100.bdf"
call bdf2ufont %UFARGS% "bdf/UnicodeM16.bdf"
call bdf2ufont %UFARGS% "bdf/unifont16.bdf"
call bdf2ufont %UFARGS% "bdf/unifont28.bdf"
call bdf2ufont %UFARGS% "bdf/unifont32.bdf"
call bdf2ufont %UFARGS% "bdf/unifont40.bdf"
call bdf2ufont %UFARGS% "bdf/unifont50.bdf"
call bdf2ufont %UFARGS% "bdf/utopia_b12.bdf"
call bdf2ufont %UFARGS% "bdf/utopia_b24.bdf"
call bdf2ufont %UFARGS% "bdf/WaveeWeekend-Normal28.bdf"
call bdf2ufont %UFARGS% "bdf/WaveeWeekend-Normal38.bdf"
call bdf2ufont %UFARGS% "bdf/wenquanyi9.bdf"
call bdf2ufont %UFARGS% "bdf/wenquanyi12.bdf"
call bdf2ufont %UFARGS% "bdf/wenquanyi36.bdf"
call bdf2ufont %UFARGS% "bdf/wqy-unibit16.bdf"
call bdf2ufont %UFARGS% "bdf/yadou.otf36.bdf"
call bdf2ufont %UFARGS% "bdf/Zenon96.bdf"
call bdf2ufont %UFARGS% "bdf/Zenon160.bdf"
call bdf2ufont %UFARGS% "bdf/ZenonCondensed52.bdf"
call bdf2ufont %UFARGS% "bdf/ZeroThrees20.bdf"
call bdf2ufont %UFARGS% "bdf/ZeroThrees32.bdf"
call bdf2ufont %UFARGS% "bdf/ZeroThrees84.bdf"
call bdf2ufont %UFARGS% "bdf/ZeroThrees160.bdf"
call bdf2ufont %UFARGS% "bdf/zxspectrum16.bdf"
call bdf2ufont %UFARGS% "bdf/NicoMoji-Regular.ttf160.bdf"
call bdf2ufont %UFARGS% "bdf/NicoMoji-Regular.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/Rationale-Regular.ttf102.bdf"
call bdf2ufont %UFARGS% "bdf/Rationale-Regular.ttf190.bdf"
call bdf2ufont %UFARGS% "bdf/Rationale-Regular.ttf250.bdf"
call bdf2ufont %UFARGS% "bdf/Rationale-Regular.ttf280.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf10.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf11.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf12.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf14.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf16.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf18.bdf"
call bdf2ufont %UFARGS% "bdf/lucida.ttf20.bdf"
call bdf2ufont %UFARGS% "bdf/seguisymbols.ttf34.bdf"
call bdf2ufont %UFARGS% "bdf/Adventure Subtitles.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/Alloy Bold.ttf170.bdf"
call bdf2ufont %UFARGS% "bdf/Ravebold.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/Thong.ttf26.bdf"
call bdf2ufont %UFARGS% "bdf/Thong.ttf30.bdf"
call bdf2ufont %UFARGS% "bdf/Thong.ttf36.bdf"
call bdf2ufont %UFARGS% "bdf/Thong.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/Thong.ttf220.bdf"
call bdf2ufont %UFARGS% "bdf/kimidori mugcup.ttf31.bdf"
call bdf2ufont %UFARGS% "bdf/kimidori mugcup.ttf62.bdf"
call bdf2ufont %UFARGS% "bdf/Alba Super.ttf64.bdf"
call bdf2ufont %UFARGS% "bdf/Ambiance BT Coalesce.ttf24.bdf"
call bdf2ufont %UFARGS% "bdf/Ambiance BT Coalesce.ttf33.bdf"
call bdf2ufont %UFARGS% "bdf/Ambiance BT Coalesce.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf24.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf28.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf50.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf162.bdf"
call bdf2ufont %UFARGS% "bdf/Astute Caps.ttf180.bdf"
call bdf2ufont %UFARGS% "bdf/Athletic.ttf52.bdf"
call bdf2ufont %UFARGS% "bdf/Athletic.ttf84.bdf"
call bdf2ufont %UFARGS% "bdf/Athletic.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/Break.ttf72.bdf"
call bdf2ufont %UFARGS% "bdf/Break.ttf84.bdf"
call bdf2ufont %UFARGS% "bdf/Break.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/Buffet Script.otf52.bdf"
call bdf2ufont %UFARGS% "bdf/Butterfly.otf52.bdf"
call bdf2ufont %UFARGS% "bdf/Butterfly.otf72.bdf"
call bdf2ufont %UFARGS% "bdf/Butterfly.otf84.bdf"
call bdf2ufont %UFARGS% "bdf/CCPhasesOnStun.ttf52.bdf"
call bdf2ufont %UFARGS% "bdf/CCPhasesOnStun.ttf96.bdf"
call bdf2ufont %UFARGS% "bdf/CD-Icons.ttf96.bdf"

