@echo off

REM recalculate verticalPitch, realligning maximum height of glyphs to the largest digit
REM
REM Use this after removing glpyh(s) from a font in reset global font metrics
REM


call uflookup "uf_Digits/04b_03-8.uf" -p
call uflookup "uf_Digits/04b_03b-8.uf" -p
call uflookup "uf_Digits/04b_08-8.uf" -p
call uflookup "uf_Digits/10x20.uf" -p 
call uflookup "uf_Digits/11s0blt.uf" -p 
call uflookup "uf_Digits/198five132.uf" -p
call uflookup "uf_Digits/52sphereoids40.uf" -p
call uflookup "uf_Digits/5x7.uf" -p 
call uflookup "uf_Digits/5x8.uf" -p 
call uflookup "uf_Digits/6px2bus12.uf" -p
call uflookup "uf_Digits/6x10.uf" -p
call uflookup "uf_Digits/6x12.uf" -p
call uflookup "uf_Digits/6x13.uf" -p
call uflookup "uf_Digits/76london28.uf" -p
call uflookup "uf_Digits/76london38.uf" -p
call uflookup "uf_Digits/76london84.uf" -p
call uflookup "uf_Digits/7x13.uf" -p
call uflookup "uf_Digits/7x14.uf" -p
call uflookup "uf_Digits/8x13.uf" -p
call uflookup "uf_Digits/9x18.uf" -p
call uflookup "uf_Digits/actionman132.uf" -p
call uflookup "uf_Digits/adventuresubtitles180.uf" -p
call uflookup "uf_Digits/alliedenginegreased96.uf" -p
call uflookup "uf_Digits/alloybold170.uf" -p
call uflookup "uf_Digits/amazdoomrightoutline72.uf" -p 
call uflookup "uf_Digits/androidclock111.uf" -p
call uflookup "uf_Digits/androidclock180.uf" -p
call uflookup "uf_Digits/androidclock32.uf" -p
call uflookup "uf_Digits/arial16.uf" -p 
call uflookup "uf_Digits/assemblerbold52.uf" -p
call uflookup "uf_Digits/astronomicmono36.uf" -p
call uflookup "uf_Digits/atari-small.uf" -p
call uflookup "uf_Digits/bauhaus-demi20.uf" -p
call uflookup "uf_Digits/bauhaus-demi36.uf" -p
call uflookup "uf_Digits/berlinergroteskbq-light34.uf" -p
call uflookup "uf_Digits/berlinergroteskbq-light96.uf" -p
call uflookup "uf_Digits/cachetstd-bold180.uf" -p
call uflookup "uf_Digits/cachetstd-bold214.uf" -p
call uflookup "uf_Digits/cgyearbooksolid180.uf" -p 
call uflookup "uf_Digits/circled51.uf" -p
call uflookup "uf_Digits/clipebold190.uf" -p
call uflookup "uf_Digits/clock92.uf" -p 
call uflookup "uf_Digits/collegiateblackflf170.uf" -p
call uflookup "uf_Digits/colonywarsnormal72.uf" -p 
call uflookup "uf_Digits/comicsans20.uf" -p
call uflookup "uf_Digits/commadornormal160.uf" -p
call uflookup "uf_Digits/commadorwidenormal160.uf" -p
call uflookup "uf_Digits/consola14.uf" -p
call uflookup "uf_Digits/consola24.uf" -p
call uflookup "uf_Digits/consola40.uf" -p
call uflookup "uf_Digits/consola96.uf" -p
call uflookup "uf_Digits/continuummedium18.uf" -p
call uflookup "uf_Digits/continuummedium33.uf" -p
call uflookup "uf_Digits/corneliusmaurits34.uf" -p 
call uflookup "uf_Digits/courr24.uf" -p 
call uflookup "uf_Digits/cu12.uf" -p
call uflookup "uf_Digits/curveless38.uf" -p
call uflookup "uf_Digits/dejavusans11.uf" -p
call uflookup "uf_Digits/dejavusans16.uf" -p
call uflookup "uf_Digits/dejavusans20.uf" -p
call uflookup "uf_Digits/dejavusans26.uf" -p
call uflookup "uf_Digits/dejavusans30.uf" -p
call uflookup "uf_Digits/dejavusans36.uf" -p
call uflookup "uf_Digits/efont_b24.uf" -p
call uflookup "uf_Digits/etl24.uf" -p 
call uflookup "uf_Digits/eurocaps24.uf" -p
call uflookup "uf_Digits/eurocaps34.uf" -p
call uflookup "uf_Digits/eurocaps44.uf" -p
call uflookup "uf_Digits/eurocaps52.uf" -p
call uflookup "uf_Digits/eurocaps72.uf" -p
call uflookup "uf_Digits/eurocaps96.uf" -p
call uflookup "uf_Digits/freesans108.uf" -p
call uflookup "uf_Digits/freesans12.uf" -p
call uflookup "uf_Digits/freesans18.uf" -p
call uflookup "uf_Digits/freesans32.uf" -p
call uflookup "uf_Digits/freesans40.uf" -p
call uflookup "uf_Digits/freesans52.uf" -p
call uflookup "uf_Digits/freesans72.uf" -p
call uflookup "uf_Digits/futurehebold50.uf" -p
call uflookup "uf_Digits/geoplainhollow32.uf" -p
call uflookup "uf_Digits/gosmicksans30.uf" -p
call uflookup "uf_Digits/gosmicksans50.uf" -p
call uflookup "uf_Digits/gosmicksans92.uf" -p
call uflookup "uf_Digits/heberlingcasualnfbold30.uf" -p
call uflookup "uf_Digits/heberlingcasualnfbold50.uf" -p
call uflookup "uf_Digits/helvr12.uf" -p 
call uflookup "uf_Digits/helvr24.uf" -p 
call uflookup "uf_Digits/jhm_b34.uf" -p 
call uflookup "uf_Digits/lcdregular51.uf" -p
call uflookup "uf_Digits/legacyserifmditcttmedium28.uf" -p 
call uflookup "uf_Digits/legacyserifmditcttmedium34.uf" -p 
call uflookup "uf_Digits/legacyserifmditcttmedium40.uf" -p 
call uflookup "uf_Digits/legacyserifmditcttmedium72.uf" -p 
call uflookup "uf_Digits/legacyserifmditcttmedium84.uf" -p 
call uflookup "uf_Digits/leger-regular16.uf" -p
call uflookup "uf_Digits/leger-regular33.uf" -p
call uflookup "uf_Digits/levenimmt132.uf" -p
call uflookup "uf_Digits/lucida10.uf" -p
call uflookup "uf_Digits/lucida11.uf" -p
call uflookup "uf_Digits/lucida12.uf" -p
call uflookup "uf_Digits/lucida14.uf" -p
call uflookup "uf_Digits/lucida16.uf" -p
call uflookup "uf_Digits/lucida18.uf" -p
call uflookup "uf_Digits/lucida20.uf" -p
call uflookup "uf_Digits/luftwafferegular32.uf" -p 
call uflookup "uf_Digits/luftwafferegular40.uf" -p 
call uflookup "uf_Digits/luftwafferegular72.uf" -p 
call uflookup "uf_Digits/luftwafferegular96.uf" -p 
call uflookup "uf_Digits/luggageroundregular36.uf" -p
call uflookup "uf_Digits/madscientist32.uf" -p
call uflookup "uf_Digits/madscientist34.uf" -p
call uflookup "uf_Digits/maetl40.uf" -p 
call uflookup "uf_Digits/maetllight30.uf" -p
call uflookup "uf_Digits/maetllight32.uf" -p
call uflookup "uf_Digits/mainframebb14.uf" -p
call uflookup "uf_Digits/mainframebb24.uf" -p
call uflookup "uf_Digits/mainframebb36.uf" -p
call uflookup "uf_Digits/maitai36.uf" -p
call uflookup "uf_Digits/maitai96.uf" -p
call uflookup "uf_Digits/malstockitctt92.uf" -p
call uflookup "uf_Digits/masexy32.uf" -p
call uflookup "uf_Digits/microtechnicextoutline32.uf" -p 
call uflookup "uf_Digits/microtechnicextoutline36.uf" -p 
call uflookup "uf_Digits/midevilnormal36.uf" -p
call uflookup "uf_Digits/milleniumbdexbtboldextended50.uf" -p
call uflookup "uf_Digits/mingliu44.uf" -p
call uflookup "uf_Digits/missellen36.uf" -p
call uflookup "uf_Digits/namco36.uf" -p 
call uflookup "uf_Digits/namco91.uf" -p 
call uflookup "uf_Digits/nanosecondthickbrk100.uf" -p
call uflookup "uf_Digits/nanosecondthickbrk180.uf" -p
call uflookup "uf_Digits/nanosecondthickbrk20.uf" -p 
call uflookup "uf_Digits/nanosecondthickbrk44.uf" -p 
call uflookup "uf_Digits/nanosecondthickbrk84.uf" -p 
call uflookup "uf_Digits/nanosecondthinbrk100.uf" -p 
call uflookup "uf_Digits/nanosecondthinbrk16.uf" -p
call uflookup "uf_Digits/nanosecondthinbrk180.uf" -p 
call uflookup "uf_Digits/nanosecondthinbrk31.uf" -p
call uflookup "uf_Digits/nanosecondthinbrk40.uf" -p
call uflookup "uf_Digits/nanosecondthinbrk84.uf" -p
call uflookup "uf_Digits/ncenr10.uf" -p 
call uflookup "uf_Digits/neuropolitical24.uf" -p
call uflookup "uf_Digits/neuropolitical28.uf" -p
call uflookup "uf_Digits/neuropolitical40.uf" -p
call uflookup "uf_Digits/nicomoji-regular160.uf" -p
call uflookup "uf_Digits/nicomoji-regular180.uf" -p
call uflookup "uf_Digits/nimbus14.uf" -p
call uflookup "uf_Digits/notoserif36.uf" -p
call uflookup "uf_Digits/orbiteer-bold30.uf" -p
call uflookup "uf_Digits/orbonitcstd16.uf" -p
call uflookup "uf_Digits/orbonitcstd32.uf" -p
call uflookup "uf_Digits/proof9x16.uf" -p
call uflookup "uf_Digits/quarxoutline26.uf" -p
call uflookup "uf_Digits/quarxoutline40.uf" -p
call uflookup "uf_Digits/querroundregular150.uf" -p
call uflookup "uf_Digits/querroundregular33.uf" -p 
call uflookup "uf_Digits/querroundregular96.uf" -p 
call uflookup "uf_Digits/racer102.uf" -p
call uflookup "uf_Digits/racer140.uf" -p
call uflookup "uf_Digits/racer180.uf" -p
call uflookup "uf_Digits/rationale-regular102.uf" -p 
call uflookup "uf_Digits/rationale-regular190.uf" -p 
call uflookup "uf_Digits/rationale-regular250.uf" -p 
call uflookup "uf_Digits/rationale-regular280.uf" -p 
call uflookup "uf_Digits/ravebold180.uf" -p
call uflookup "uf_Digits/razer.uf" -p 
call uflookup "uf_Digits/reversionbroken34.uf" -p
call uflookup "uf_Digits/revuehollow180.uf" -p
call uflookup "uf_Digits/riskbold38.uf" -p
call uflookup "uf_Digits/rought18.uf" -p
call uflookup "uf_Digits/savedbyzero24.uf" -p
call uflookup "uf_Digits/savedbyzero50.uf" -p
call uflookup "uf_Digits/schwabenaltbold40.uf" -p
call uflookup "uf_Digits/schwabenaltbold72.uf" -p
call uflookup "uf_Digits/screen8x16.uf" -p
call uflookup "uf_Digits/seguisymbols34.uf" -p
call uflookup "uf_Digits/shadow-bold.uf" -p
call uflookup "uf_Digits/shadow.uf" -p
call uflookup "uf_Digits/sinsabold40.uf" -p
call uflookup "uf_Digits/sinsofficinasans84.uf" -p 
call uflookup "uf_Digits/snap.uf" -p
call uflookup "uf_Digits/teutonweiss-bold109.uf" -p
call uflookup "uf_Digits/teutonweiss-bold132.uf" -p
call uflookup "uf_Digits/teutonweiss-bold180.uf" -p
call uflookup "uf_Digits/teutonweiss-bold28.uf" -p 
call uflookup "uf_Digits/teutonweiss-bold34.uf" -p 
call uflookup "uf_Digits/teutonweiss-bold50.uf" -p 
call uflookup "uf_Digits/teutonweiss-bold84.uf" -p 
call uflookup "uf_Digits/teutonweiss28.uf" -p
call uflookup "uf_Digits/teutonweiss34.uf" -p
call uflookup "uf_Digits/teutonweiss50.uf" -p
call uflookup "uf_Digits/teutonweiss84.uf" -p
call uflookup "uf_Digits/times16.uf" -p 
call uflookup "uf_Digits/tlwgtypewriter50.uf" -p
call uflookup "uf_Digits/ubuntu-l20.uf" -p
call uflookup "uf_Digits/ubuntu-l24.uf" -p
call uflookup "uf_Digits/ubuntu-r12.uf" -p
call uflookup "uf_Digits/ubuntu-r32.uf" -p
call uflookup "uf_Digits/ubuntumono-r36.uf" -p
call uflookup "uf_Digits/unicode100.uf" -p
call uflookup "uf_Digits/unicode18.uf" -p
call uflookup "uf_Digits/unicode36.uf" -p
call uflookup "uf_Digits/unicode50.uf" -p
call uflookup "uf_Digits/unicode72.uf" -p
call uflookup "uf_Digits/unicodem16.uf" -p
call uflookup "uf_Digits/unifont16.uf" -p
call uflookup "uf_Digits/unifont28.uf" -p
call uflookup "uf_Digits/unifont32.uf" -p
call uflookup "uf_Digits/unifont40.uf" -p
call uflookup "uf_Digits/unifont50.uf" -p
call uflookup "uf_Digits/utopia_b12.uf" -p
call uflookup "uf_Digits/utopia_b24.uf" -p
call uflookup "uf_Digits/waveeweekend-normal28.uf" -p
call uflookup "uf_Digits/waveeweekend-normal38.uf" -p
call uflookup "uf_Digits/wenquanyi12.uf" -p
call uflookup "uf_Digits/wenquanyi36.uf" -p
call uflookup "uf_Digits/wenquanyi9.uf" -p
call uflookup "uf_Digits/wqy-unibit16.uf" -p
call uflookup "uf_Digits/yadou36.uf" -p 
call uflookup "uf_Digits/zenon160.uf" -p
call uflookup "uf_Digits/zenon96.uf" -p 
call uflookup "uf_Digits/zenoncondensed52.uf" -p
call uflookup "uf_Digits/zerothrees160.uf" -p
call uflookup "uf_Digits/zerothrees20.uf" -p
call uflookup "uf_Digits/zerothrees32.uf" -p
call uflookup "uf_Digits/zerothrees84.uf" -p
call uflookup "uf_Digits/zxspectrum16.uf" -p